### ISSUE TITLE
Safari hides text after hover effect

### ISSUE THREAD

**Issue by shoored** [tailwindlabs/tailwindcss-line-clamp#19] opened 2022-05-12 15:18 UTC
### What version of @tailwindcss/line-clamp are you using?

0.4.0

### What version of Node.js are you using?

14.19.2

### What browser are you using?

Safari

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/AKeOAzNk7c

### Describe your issue

Hello! 

I've come across a weird bug in Safari. Not sure if it's a Safari thing, it seems like it. I'm having a hard time finding the root cause. 

In first load, all seems well. The text is clamped, like in other browsers.
When hovering over the card, the line-clamp is reset to none, that also works like expected. Phew.
However, when returning to the non-hover view, the text block is suddenly invisible / gone. 

I did not have this issue myself in Safari 14 or even 15.not.the.latest.
In Safari 15.the.latest I can reproduce the bug like my client mentioned.

I'm on the latest Tailwind, it works well in Brave, Firefox.

**Comment by adamwathan** [comment] 2022-05-13 10:55
Thanks for reporting! Spent some time digging in to this and was able to reduce the reproduction to this:

https://jsfiddle.net/d3nqryke/

The key ingredients are removing line-clamp on hover _and_ changing the text color at the same time.

Unfortunately though as demonstrated in the example above, this doesn't seem specific to Tailwind — just seems like a Safari CSS bug that happens even with very simple vanilla CSS. I don't think there's anything we can change here about the CSS implementation either, all of those properties are needed for line clamping to work and I don't know of any other way to do it 😕

We found out about another Safari 15.4 bug a little while ago that has the same sort of flavor as this one to me, where some graphical stuff is just not rendering properly:

https://twitter.com/adamwathan/status/1505165679749701637

In the [WebKit issue](https://bugs.webkit.org/show_bug.cgi?id=238088#c4) one of the maintainers mentions that it's a bug in an underlying graphics framework that they are tracking internally. I'd bet this line-clamp issue is the result of the same issue, since both only exist specifically in Safari 15.4 and involve things vanishing off the screen.

I'll ask someone on the team to report this as a WebKit bug regardless to make sure it gets seen though 👍🏻

**Comment by thecrypticace** [comment] 2022-05-14 02:56
I've done a bit more investigation and [filed a bug report with webkit](https://bugs.webkit.org/show_bug.cgi?id=240410). I spent a bit of time trying to create a workaround but unfortunately I was not able to. Closing since this is a webkit bug and there's no further action we can take on it unfortunately. I really appreciate you bringing it to our attention!

**Closed as completed by thecrypticace** 2022-05-14 02:56 UTC

**Comment by shoored** [comment] 2022-05-15 09:24
Thank you both for the time working on this silly bug. It's really appreciated, especially since it's not really a Tailwind issue. What amazing support. Thanks a million!
