### ISSUE TITLE
Tailwind CSSv3.0.23+ doesn't properly support variants

### ISSUE THREAD

**Issue by benlei** [tailwindlabs/tailwindcss-line-clamp#18] opened 2022-04-25 00:37 UTC
### What version of @tailwindcss/line-clamp are you using?

v0.3.1

### What version of Node.js are you using?

v16.13.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

N/A

### Describe your issue

Cont of #16 

@adamwathan the issue is that varaints aren't working (aren't generated) with the above versions (with Tailwind CSSv3.0.23) I mentioned. Tailwind renamed the `variants` field to `addVariant`, which is why the existing `variant` field won't work in getting the the variant CSS code generated.

**Comment by adamwathan** [comment] 2022-04-25 00:57
You gotta provide a reproduction man otherwise I have no idea what you are trying to tell me. `variants` was not renamed to `addVariant`, those are two totally different functions.

Line clamp utilities do support variants in Tailwind v3, try `hover:line-clamp-2` and it will just work, no variants configuration necessary because every variant works everywhere in v3. So you’re gonna need to provide a reproduction for me to understand what you actually mean when you say “not working” because it does work 😅

**Comment by adamwathan** [comment] 2022-04-25 01:07
Here's a demo where you can see Tailwind v3.0.24 + the line-clamp plugin with variants working out of the box with no configuration necessary:

https://play.tailwindcss.com/V25ihYtsG6

So what is the actual problem you have in your project that isn't working? Happy to help with that but you have to tell me what it is you know? ❤️

**Comment by adamwathan** [comment] 2022-04-25 15:56
Going to close this, feel free to [open a discussion](https://github.com/tailwindlabs/tailwindcss/discussions) if you need help with something specific though, always happy to help.

**Closed as completed by adamwathan** 2022-04-25 15:56 UTC

**Comment by benlei** [comment] 2022-04-27 00:26
@adamwathan  see https://play.tailwindcss.com/91ENbypV2a

```
hover:line-clamp-[3]
```
is the offending bit

**Comment by adamwathan** [comment] 2022-04-27 00:54
Hey thanks for the extra detail! So the issue isn't actually anything to do with variants, it's that the latest release of the line-clamp plugin doesn't support arbitrary values:

https://play.tailwindcss.com/91ENbypV2a

The good news is support _has_ been added for this:

https://github.com/tailwindlabs/tailwindcss-line-clamp/pull/10

...it's just that we haven't cut a release. Made a note to cut one tomorrow though!
